### ISSUE TITLE
add_host bastion VM so ansible can use it

### ISSUE THREAD

**Issue by brusMX** [zikalino/openshift-work#16]
Dynamically we will have to: 
- Provision a bastion VM -  #13 by @asinn826 
- Create a new pair of SSH keys
- Propagate the SSH keys to the other VMs with[ authorized_keys module](https://stackoverflow.com/questions/25629933/ansible-copy-ssh-key-from-one-host-to-another)
- Add it to the ansible host list so it can perform actions like adding running the Openshift provisioning playbook and running verifications on the other VMs 

   ``` yaml  
    - name: Add new instance to host group
         add_host:
           hostname: "{{ item['ips'][0].public_ip }}"
           groupname: azure_vms
         with_items: "{{ azure.deployment.instances }}"
   ```
